#!/usr/bin/env bash

tmp_dir="/tmp/cliphist"
rm -rf "$tmp_dir"

if [[ -n "$1" ]]; then
    read -r id ext <<< "${1//$'\t'/ }"
    
    mime=""
    case "$ext" in
        png) mime="image/png" ;;
        jpg|jpeg) mime="image/jpeg" ;;
        bmp) mime="image/bmp" ;;
    esac
    
    if [[ -n "$mime" ]]; then
        echo -n "$id" | cliphist decode | wl-copy --type "$mime"
    else
        echo -n "$id" | cliphist decode | wl-copy
    fi
    exit
fi

mkdir -p "$tmp_dir"

read -r -d '' prog <<EOF
/^[0-9]+\s<meta http-equiv=/ { next }
match(\$0, /^([0-9]+)\s(\[\[\s)?binary.*(jpg|jpeg|png|bmp)/, grp) {
    system("echo -n " grp[1] " | cliphist decode > " tmp_dir "/" grp[1] "." grp[3])
    print grp[1] "\t" grp[3] "\0icon\x1f" tmp_dir "/" grp[1] "." grp[3]
    next
}
EOF

cliphist list | gawk -v tmp_dir="$tmp_dir" "$prog"
