[manager]
sort_by      = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
image_origin    = "kitty"
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_margin = 0

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "Edit" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, desc = "Play" },
]
image = [
	{ run = 'feh "$@"', orphan = true, desc = "View" },
]
pdf = [
	{ run = 'zathura "$@"', orphan = true, desc = "View PDF" },
]
web = [
	{ run = 'uwsm app -- helium-browser "$@"', orphan = true, desc = "Open in Helium" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
	# 1. High Priority System/Code Types
	{ mime = "inode/x-empty", use = "edit" },
	{ name = "*.qml", use = "edit" },
	{ name = "*.lua", use = "edit" },
	{ name = "*.txt", use = "edit" },
	{ name = "*.json", use = "edit" },
	{ name = "*.js", use = "edit" },
  { mime = "image/svg+xml", use = ["edit", "image"] },

	# 2. Broader Mime Types
	{ mime = "text/*", use = "edit" },
	{ mime = "application/javascript", use = "edit" },
	{ mime = "application/json", use = "edit" },
	{ mime = "application/x-shellscript", use = "edit" },

	# 3. Multimedia & Others
	{ name = "*.html", use = "web" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "play" },
	{ mime = "audio/*", use = "play" },
	{ mime = "application/pdf", use = "pdf" },
	{ mime = "inode/directory", use = "open" },

	# 4. Binary/Exec Safety
	{ mime = "application/octet-stream", use = "open" },
	{ name = "*", is = "exec", use = "open" },

	# 5. Global Fallback
	{ name = "*", use = "edit" },
    { mime = "*", use = "edit" },
]

# --- MEDIAINFO ---
[[plugin.prepend_preloaders]]
mime = "{audio,video,image}/*"
run  = "mediainfo"

[[plugin.prepend_preloaders]]
mime = "application/subrip"
run  = "mediainfo"

[[plugin.prepend_previewers]]
mime = "{audio,video,image}/*"
run  = "mediainfo"

[[plugin.prepend_previewers]]
mime = "application/subrip"
run  = "mediainfo"

# --- GIT ---
[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"

# --- OUCH ---
[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"

# --- RICH-PREVIEW --- 
[[plugin.prepend_previewers]]
url = "*.csv"
run = "rich-preview"

[[plugin.prepend_previewers]]
url = "*.md"
run = "rich-preview"

[[plugin.prepend_previewers]]
url = "*.rst"
run = "rich-preview"

[[plugin.prepend_previewers]]
url = "*.ipynb"
run = "rich-preview"

[[plugin.prepend_previewers]]
url = "*.json"
run = "rich-preview"
