#    ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗ 
#    ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
#    ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
#    ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
#    ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
#    ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
# By: LRuego
# --------------------------------------------------------------------------

# Wallpaper Configuration (0.8.0 syntax)
wallpaper {
    monitor = HDMI-A-1
    path = /home/lruego/Pictures/Wallpapers/BLACK by Jean-Marc Denis/BLACK_IX_REMIX-desktop.jpg
}

# Enable splash text rendering over the wallpaper
splash = false

ipc = on
